services:
  docusaurus:
    build: .
    container_name: averagejoeslab-dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped